# Generated by Django 2.2.5 on 2019-09-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataListener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='incidentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=50)),
                ('pattern_string', models.CharField(max_length=50)),
                ('words_caught', models.CharField(max_length=50)),
                ('message_sent', models.CharField(max_length=50)),
            ],
        ),
    ]
