# Generated by Django 2.2.5 on 2019-09-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataListener', '0002_incidentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentlog',
            name='message_sent',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='pattern_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='pattern_string',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='words_caught',
            field=models.CharField(max_length=100),
        ),
    ]
